<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;
use Faker\Factory;

class Cliente extends AbstractSeed
{
    public function run(): void
    {
        $this->execute('SET FOREIGN_KEY_CHECKS=0;');
        $table = $this->table('cliente');
        $table->truncate();
        $faker = Factory::create();
        $data = [
            [
			    'id_cliente' => 1,
                'id_gimnasio' => 1,
                'id_planGym' => 1,
                'nombre_cliente' => 'Erika',
                'apellido_paterno_cliente' => 'Lopez',
                'apellido_materno_cliente' => 'Velasco',
                'municipio_cliente' => 'Tecamac',
                'colonia_cliente' => 'Felipe villa Nueva',
                'calle_cliente' => 'Calvario',
                'codigo_postal_cliente' => '55740',
                'numero_cliente' => '5589098567',
                'imagen_cliente' => 'imagen3.jpg',
                'email_cliente' => 'eri@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
            [
			    'id_cliente' => 2,
                'id_gimnasio' => 1,
                'id_planGym' => 2,
                'nombre_cliente' => 'Martin',
                'apellido_paterno_cliente' => 'Garcia',
                'apellido_materno_cliente' => 'Martinez',
                'municipio_cliente' => 'Tecamac',
                'colonia_cliente' => 'tecamac',
                'calle_cliente' => '5 de Marzo',
                'codigo_postal_cliente' => '55740',
                'numero_cliente' => '7754323456',
                'imagen_cliente' => 'imagen1.jpg',
                'email_cliente' => 'martin@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
            [
			    'id_cliente' => 3,
                'id_gimnasio' => 1,
                'id_planGym' => 3,
                'nombre_cliente' => 'Cecilia',
                'apellido_paterno_cliente' => 'Lopez',
                'apellido_materno_cliente' => 'Garcia',
                'municipio_cliente' => 'Texcoco',
                'colonia_cliente' => 'Centro',
                'calle_cliente' => 'Boca negra',
                'codigo_postal_cliente' => '66789',
                'numero_cliente' => '7765432457',
                'imagen_cliente' => 'imagen10.jpg',
                'email_cliente' => 'ceci@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
            [
			    'id_cliente' => 4,
                'id_gimnasio' => 2,
                'id_planGym' => 4,
                'nombre_cliente' => 'Monserat',
                'apellido_paterno_cliente' => 'Osorio',
                'apellido_materno_cliente' => 'Lopez',
                'municipio_cliente' => 'tecamac',
                'colonia_cliente' => 'Felipe villa Nueva',
                'calle_cliente' => 'Calvario',
                'codigo_postal_cliente' => '55740',
                'numero_cliente' => '5567865434',
                'imagen_cliente' => 'imagen10.jpg',
                'email_cliente' => 'monse@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
            [
			    'id_cliente' => 5,
                'id_gimnasio' => 2,
                'id_planGym' => 5,
                'nombre_cliente' => 'Gerardo',
                'apellido_paterno_cliente' => 'Garcia',
                'apellido_materno_cliente' => 'San juan',
                'municipio_cliente' => 'Tecamac',
                'colonia_cliente' => 'tecamac',
                'calle_cliente' => 'Calvario',
                'codigo_postal_cliente' => '55740',
                'numero_cliente' => '5678765432',
                'imagen_cliente' => 'imagen9.jpg',
                'email_cliente' => 'gerardo@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
            [
			    'id_cliente' => 6,
                'id_gimnasio' => 2,
                'id_planGym' => 6,
                'nombre_cliente' => 'Alberto',
                'apellido_paterno_cliente' => 'Perez',
                'apellido_materno_cliente' => 'Perez',
                'municipio_cliente' => 'San Juan',
                'colonia_cliente' => '5 De mayo',
                'calle_cliente' => 'cen',
                'codigo_postal_cliente' => '89876',
                'numero_cliente' => '897654345',
                'imagen_cliente' => null,
                'email_cliente' => 'aberto@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
            [
			    'id_cliente' => 7,
                'id_gimnasio' => 3,
                'id_planGym' => 7,
                'nombre_cliente' => 'Luciana',
                'apellido_paterno_cliente' => 'López',
                'apellido_materno_cliente' => 'San juan',
                'municipio_cliente' => 'San Bartolo',
                'colonia_cliente' => 'Centro',
                'calle_cliente' => '5 de Agosto',
                'codigo_postal_cliente' => '55740',
                'numero_cliente' => '7719028008',
                'imagen_cliente' => 'imagen4.jpg',
                'email_cliente' => 'lucia@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
            [
			    'id_cliente' => 8,
                'id_gimnasio' => 3,
                'id_planGym' => 8,
                'nombre_cliente' => 'Gerardo',
                'apellido_paterno_cliente' => 'Garcia',
                'apellido_materno_cliente' => 'Martinez',
                'municipio_cliente' => 'Tecamac',
                'colonia_cliente' => 'Felipe villa Nueva',
                'calle_cliente' => '5 de Marzo',
                'codigo_postal_cliente' => '55740',
                'numero_cliente' => '7754323456',
                'imagen_cliente' => 'imagen7.jpg',
                'email_cliente' => 'gera@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
            [
			    'id_cliente' => 9,
                'id_gimnasio' => 4,
                'id_planGym' => 10,
                'nombre_cliente' => 'Jesus',
                'apellido_paterno_cliente' => 'Lopez',
                'apellido_materno_cliente' => 'Martinez',
                'municipio_cliente' => 'Tecamac',
                'colonia_cliente' => 'tecamac',
                'calle_cliente' => '5 de Marzo',
                'codigo_postal_cliente' => '55740',
                'numero_cliente' => '7719028008',
                'imagen_cliente' => 'imagen7.jpg',
                'email_cliente' => 'jeus@gmail.com',
                'is_email_notified' => 0,
                'is_active' => 0,
            ],
        ];

        for ($i = count($data) + 1; $i <= 60; $i++) {
            $data[] = [
                'id_cliente' => $i,
                'id_gimnasio' => 2,
                'id_planGym' => $faker->randomElement([4, 5, 6]),
                'nombre_cliente' => $faker->firstName,
                'apellido_paterno_cliente' => $faker->lastName,
                'apellido_materno_cliente' => $faker->lastName,
                'municipio_cliente' => $faker->city,
                'colonia_cliente' => $faker->word,
                'calle_cliente' => $faker->streetAddress,
                'codigo_postal_cliente' => $faker->postcode,
                'numero_cliente' => $faker->phoneNumber,
                'imagen_cliente' => null,
                'email_cliente' => $faker->email,
                'is_email_notified' => 0,
                'is_active' => 0,
            ];
        }

        $table->insert($data)->save();

    }
}
